[versions]
allaymc-nodejs-runtime = "0.0.1-alpha"
allaymc-server = "0.1.3"

kotlin = "2.1.0"
gradleup-shadow = "8.3.0"

kotlinx-coroutines = "1.10.1"

caoccao-javet = "4.1.1"

[libraries]
allaymc-server = { group = "org.allaymc.allay", name = "server", version.ref = "allaymc-server" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

caoccao-javet = { group = "com.caoccao.javet", name = "javet", version.ref = "caoccao-javet" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradleup-shadow = { id = "com.gradleup.shadow", version.ref = "gradleup-shadow" }
