name: Build a preview version
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :script-loader:shadowJar

      - name: Upload artifact (loader)
        uses: actions/upload-artifact@v4
        with:
          name: kts-loader-${{ github.sha }}
          path: script-loader/build/libs/*.jar
